import { nanoid } from 'nanoid';


const SongData = [
    {   
        title: "After You've Gone",
        year: 1936,
        bpm: '131',
        songKey: 'G Major',
        youtubeUrl: 'https://www.youtube.com/watch?v=BTH_Nn_TtDI',
        chords: [
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()},
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()},
            {chordName: '%', id: nanoid()},
            {chordName: 'E7', positions: 'x3231xx', firstFret: '5', id: nanoid()},
            {chordName: '%', id: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName:'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'E7', positions: 'x3231xx', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Am', positions: '133111', firstFret: '5', id: nanoid()}, 
            {chordName: 'E7', positions: 'x3231xx', firstFret: '5', id: nanoid()}, 
            {chordName: 'Am', positions: '133111', firstFret: '5', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName: 'B7', positions: '2123xx', firstFret: '6', id: nanoid()}, 
            {chordName:'Em', positions: 'x13321', firstFret: '7', id: nanoid()}, 
            {chordName: 'E<sup>o</sup>', positions: 'xx1212', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Am7', positions: '1x111x', firstFret: '5', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}
        ]
    },
    {   
        title: "Nagasaki",
        year: 1936,
        bpm: '117',
        songKey: 'G Major',
        youtubeUrl: 'https://www.youtube.com/watch?v=pUQN44doG9I',
        chords: [
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'B7', positions2: '2123xx', firstFret2: '6', id2: nanoid()},
        {chordName1: 'C', positions1: 'x13331', firstFret1: '3', id1: nanoid(), chordName2: 'Cm', positions2: 'x13321', firstFret2: '3', id2: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'D7', positions2: '2212xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'B7', positions2: '2123xx', firstFret2: '6', id2: nanoid()},
        {chordName1: 'C', positions1: 'x13331', firstFret1: '3', id1: nanoid(), chordName2: 'Cm', positions2: 'x13321', firstFret2: '3', id2: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'D7', positions2: '2212xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()},
        {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
        {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()},
        {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()},
        {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()},
        {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
        {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'Em', positions2: 'x13321', firstFret2: '7', id2: nanoid()},
        {chordName1: 'A7', positions1: '2123xx', firstFret1: '4', id1: nanoid(), chordName2: 'D7', positions2: 'x13131', firstFret2: '5', id2: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'A<sup>o</sup>', positions2: '2312xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'D7', positions: '2212xx', firstFret: '4', id: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'B7', positions2: '2123xx', firstFret2: '6', id2: nanoid()},
        {chordName1: 'C', positions1: 'x13331', firstFret1: '3', id1: nanoid(), chordName2: 'Cm', positions2: 'x13321', firstFret2: '3', id2: nanoid()},
        {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'D7', positions2: '2212xx', firstFret2: '4', id2: nanoid()},
        {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}
        
    ]
    },
    
    {   
        title: "Coucou",
        year: 1940,
        bpm: '78',
        songKey: 'A Minor',
        youtubeUrl: 'https://www.youtube.com/watch?v=0WqmkSMpqvg',
        chords: [
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()},
            {chordName: '%', id: nanoid()},
            {chordName: 'Am', positions: '133111', firstFret: '5', id: nanoid()},
            {chordName: '%', id: nanoid()}, 
            {chordName: 'F', positions: '133211', firstFret: '1', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName1: 'C', positions1: 'x13331', firstFret1: '3', id1: nanoid(), chordName2: 'Am7', positions2: '1x111x', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'Dm7', positions1: 'x13121', firstFret1: '5', id1: nanoid(), chordName2: 'G7', positions2: '2123xx', firstFret2: '2', id2: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Am', positions: '133111', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'F', positions: '133211', firstFret: '1', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C7', positions: 'x13131', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'F', positions: '133211', firstFret: '1', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'Am', positions: '133111', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'F', positions: '133211', firstFret: '1', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '(G7)', positions: '2123xx', firstFret: '2', id: nanoid()}]
    },
    {   
        title: "Melodie Au Crepuscule (Twilights Melody)",
        year: 1946,
        bpm: '99',
        songKey: 'D Major',
        youtubeUrl: 'https://www.youtube.com/watch?v=Ja3U-YR7FKw',
        chords: [
            {chordName1: 'Em', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'Em7', positions2: 'x131211', firstFret2: '7', id2: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()}, 
            {chordName: 'D', positions: 'x13331', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'E9', positions: 'x212xx', firstFret: '6', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'E♭9', positions: 'x212xx', firstFret: '5', id: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()}, 
            {chordName1: 'Em', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'Em7', positions2: 'x131211', firstFret2: '7', id2: nanoid()}, 
            {chordName1: 'A/C#', positions1: 'x1432x', firstFret1: '4', id1: nanoid(), chordName2: 'A7#5', positions2: 'xx122x', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'D', positions: 'x13331', firstFret: '5', id: nanoid()}, 
            {chordName1: 'D', positions1: 'x13331', firstFret1: '5', id1: nanoid(), chordName2: 'Bm7', positions2: '1x111x', firstFret2: '7', id2: nanoid()}, 
            {chordName: 'Em', positions: 'x3134x', firstFret: '5', id: nanoid()}, 
            {chordName1: 'E♭9', positions1: 'x212xx', firstFret1: '5', id1: nanoid(), chordName2: 'A7#5', positions2: 'xx122x', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'D <sup>6/9</sub>', positions: '221122', firstFret: '4', id: nanoid()}, 
            {chordName: '-', id: nanoid()}, 
            {chordName1: 'Em', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'Em7', positions2: 'x131211', firstFret2: '7', id2: nanoid()}, 
            {chordName1: 'A/C#', positions1: 'x1432x', firstFret1: '4', id1: nanoid(), chordName2: 'A7#5', positions2: 'xx122x', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'D', positions1: 'x13331', firstFret1: '5', id1: nanoid(), chordName2: 'Gm6', positions2: 'xx313x', firstFret2: '3', id2: nanoid()}, 
            {chordName1: 'D', positions1: 'x13331', firstFret1: '5', id1: nanoid(), chordName2: 'C#9', positions2: 'x2122x', firstFret2: '3', id2: nanoid()}, 
            {chordName1: 'F#', positions1: '133211', firstFret1: '2', id1: nanoid(), chordName2: 'D#m', positions2: 'xx212x', firstFret2: '3', id2: nanoid()}, 
            {chordName1: 'G#m7', positions1: '1x111x', firstFret1: '4', id1: nanoid(), chordName2: 'C#9', positions2: 'x2122x', firstFret2: '3', id2: nanoid()}, 
            {chordName1: 'F#6', positions1: 'xx2122', firstFret1: '3', id1: nanoid(), chordName2: 'C#9', positions2: 'x2122x', firstFret2: '3', id2: nanoid()}, 
            {chordName1: 'F#', positions1: '133211', firstFret1: '2', id1: nanoid(), chordName2: 'B7♭9', positions2: '2x121x', firstFret2: '1', id2: nanoid()}, 
            {chordName1: 'Em', positions1: 'o22ooo', firstFret1: '1', id1: nanoid(), chordName2: 'C<sup>#</sup>7/G<sup>#</sup>', positions2: '2x12xx', firstFret2: '3', id2: nanoid(), chordTwoShort: true}, 
            {chordName1: 'C7/G', positions1: '2x12xx', firstFret1: '2', id1: nanoid(), chordName2: 'B7♭9', positions2: '2x121x', firstFret2: '1', id2: nanoid()}, 
            {chordName1: 'Em', positions1: 'o22ooo', firstFret1: '1', id1: nanoid(), chordName2: 'F#7', positions2: '2123xx', firstFret2: '2', id2: nanoid(), chordTwoShort: true}, 
            {chordName: 'F7', positions: '2123xx', firstFret: '1', id: nanoid()}, 
            {chordName: 'Bm', positions: 'x13321', firstFret: '2', id: nanoid()}, 
            {chordName: 'Gm6', positions: 'xx313x', firstFret2: '3', id: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()}, 
            {chordName: '-', id: nanoid()}, 
            {chordName1: 'Em', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'Em7', positions2: 'x131211', firstFret2: '7', id2: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()},  
            {chordName: 'F#m7♭5', positions: 'xo2212', firstFret: '1', id: nanoid()}, 
            {chordName: 'B7♭9', positions: '2x121x', firstFret: '1', id: nanoid()}, 
            {chordName: 'Em', positions: 'o22ooo', firstFret: '1', id: nanoid()}, 
            {chordName1: 'E7', positions1: 'o2o1oo', firstFret1: '1', id1: nanoid(), chordName2: 'A7', positions2: 'xo2o2o', firstFret2: '1', id2: nanoid()}, 
            {chordName1: 'D', positions1: 'xxo232', firstFret1: '1', id1: nanoid(), chordName2: 'A7', positions2: 'xo2o2o', firstFret2: '1', id2: nanoid(), chordTwoShort: true}, 
            {chordName: 'D', positions: 'xxo232', firstFret: '1', id: nanoid()}
        ]
    },
    {   
        title: "Georgia On My Mind",
        year: 1936,
        bpm: '127',
        songKey: 'G Minor',
        youtubeUrl: 'https://www.youtube.com/watch?v=BqqpkQzQPns',
        chords: [
            {chordName: 'E♭', positions: 'x13331', firstFret: '6', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: 'A♭', positions1: '133211', firstFret1: '4', id1: nanoid(), chordName2: 'A♭m', positions2: '133211', firstFret2: '4', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'F#<sup>o</sup>', positions2: 'x2414x', firstFret3: '6', id2: nanoid()}, 
            {chordName1: 'Fm', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'B♭7', positions2: '2123xx', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'E<sup>o</sup>', positions2: 'x1212', firstFret2: '7', id2: nanoid()}, 
            {chordName1: 'Fm', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'B♭7', positions2: '2123xx', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'E♭', positions: 'x13331', firstFret: '6', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: 'A♭', positions1: '133211', firstFret1: '4', id1: nanoid(), chordName2: 'A♭m', positions2: '133211', firstFret2: '4', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'F#<sup>o</sup>', positions2: 'x2414x', firstFret2: '6', id2: nanoid()}, 
            {chordName1: 'Fm', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'B♭7', positions2: '2123xx', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'A♭m', positions2: '133211', firstFret2: '4', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'G7', positions2: '2123xx', firstFret2: '2', id2: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: '%', positions1: 'x13321', firstFret1: '3', id1: nanoid(), chordName2: 'G7', positions2: '2123xx', firstFret2: '2', id2: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: '%', positions1: 'x13321', firstFret1: '3', id1: nanoid(), chordName2: 'F', positions2: '133211', firstFret2: '1', id2: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: '%', positions1: 'x13321', firstFret1: '3', id1: nanoid(), chordName2: 'D7', positions2: 'x13131', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'Gm', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'G♭<sup>o</sup>', positions2: 'x3121x', firstFret2: '1', id2: nanoid()}, 
            {chordName1: 'Fm', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'B♭7', positions2: '2123xx', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'E♭', positions: 'x13331', firstFret: '6', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: 'Cm', positions: 'x13321', firstFret: '3', id: nanoid()}, 
            {chordName1: 'A♭', positions1: '133211', firstFret1: '4', id1: nanoid(), chordName2: 'A♭m', positions2: '133211', firstFret2: '4', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'F#<sup>o</sup>', positions2: 'x2414x', firstFret2: '6', id2: nanoid()}, 
            {chordName1: 'Fm', positions1: 'x13321', firstFret1: '7', id1: nanoid(), chordName2: 'B♭7', positions2: '2123xx', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'E♭', positions1: 'x13331', firstFret1: '6', id1: nanoid(), chordName2: 'A♭m', positions2: '133211', firstFret2: '4', id2: nanoid()}, 
            {chordName: 'E♭', positions: 'x13331', firstFret: '6', id: nanoid()}
        ]
    },
    {   
        title: "I Can't Give You Anything But Love",
        year: 1936,
        bpm: '116',
        songKey: 'G Major',
        youtubeUrl: 'https://www.youtube.com/watch?v=BytMZa205dU',
        chords: [
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName1: 'G/B', positions1: '31x34', firstFret1: '5', id1: nanoid(), chordName2: 'B♭<sup>o</sup>', positions2: '2x12xx', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'Am7', positions: '1x111x', firstFret: '5', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName1: 'G/B', positions1: '31x34', firstFret1: '5', id1: nanoid(), chordName2: 'B♭<sup>o</sup>', positions2: '2x12xx', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'Am7', positions: '1x111x', firstFret: '5', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'A7', positions: '2123xx', firstFret: '4', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'G', positions: '133211', firstFret: '3', id: nanoid()}, 
            {chordName1: 'G/B', positions1: '31x34', firstFret1: '5', id1: nanoid(), chordName2: 'B♭<sup>o</sup>', positions2: '2x12xx', firstFret2: '5', id2: nanoid()}, 
            {chordName: 'Am7', positions: '1x111x', firstFret: '5', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName: 'G7', positions: '2123xx', firstFret: '2', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: '%', id: nanoid()}, 
            {chordName: 'C', positions: 'x13331', firstFret: '3', id: nanoid()}, 
            {chordName: 'C#<sup>o</sup>', positions: 'x2313x', firstFret: '4', id: nanoid()},
            {chordName: 'G/D', positions: '11343', firstFret: '5', id: nanoid()}, 
            {chordName: 'E7', positions: 'x3231xx', firstFret: '5', id: nanoid()}, 
            {chordName: 'Am7', positions: '1x111x', firstFret: '5', id: nanoid()}, 
            {chordName: 'D7', positions: 'x13131', firstFret: '5', id: nanoid()}, 
            {chordName1: 'G', positions1: '133211', firstFret1: '3', id1: nanoid(), chordName2: 'E7', positions2: 'x3231xx', firstFret2: '5', id2: nanoid()}, 
            {chordName1: 'Am7', positions1: '1x111x', firstFret1: '5', id1: nanoid(), chordName2: 'D7', positions2: 'x13131', firstFret2: '5', id2: nanoid()}]
    }
   

];





export default SongData;